### PR TITLE
Local-storage

### PR DESCRIPTION
**Pull request by gilberthappi**
Use local storage to save user input.
PRmicroverse

### CODE REVIEW

**Review by julie-ify — COMMENTED** [review]
Hi @gilberthappi,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

* Your coding partner needs to contribute to the project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by gilberthappi** [comment]
but we all know that my coding partner is unavailable,, she reach to
student success and in that way i know she will not attend

**Review by Ibizugbe — COMMENTED** [review]
Hi @gilberthappi 👋🏼👋🏼👋🏼, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have contribution from pair programming partner. if your partner has reached out to student success, then you should kindly attach a screenshot of a mail from student success permitting you to work alone. If you haven't been permitted, kindly reachout to student success and talk about the issue. they will send you a mail permitting you to work alone. you can now take a screenshot of the mail and attach it to your PR description as evidence👍🏼.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by bienvenuushindi — APPROVED** [review]
Hi @gilberthappi , 

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

## HIGHLIGHTS
- No linters errors :heavy_check_mark: 
- Project document professionally :+1: 
- Good PR title and Summary :100: 
- Descriptive Readme :heavy_check_mark: 

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Pull request merged**
